routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AnimalController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::group(['middleware' => 'auth'], function () {
    // crear usuario
    Route::get('/users/create', [App\Http\Controllers\UserController::class, 'create'])->name('users.create');
    //  guardar usuario
    Route::post('/users', [App\Http\Controllers\UserController::class, 'store'])->name('users.store');
    // lista usuario
    Route::get('/users', [App\Http\Controllers\UserController::class, 'index'])->name('users.index');
    // mostrar datos de usuario
    Route::get('/users/{user}', [App\Http\Controllers\UserController::class, 'show'])->name('users.show');
    // editar usuarios
    Route::get('/users/{user}/edit', [App\Http\Controllers\UserController::class, 'edit'])->name('users.edit');
    // actualizar usuario
    Route::put('/users/{user}', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');
    // eliminar usuario
    Route::delete('/users/{user}', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.delete');
    Route::resource('posts', App\Http\Controllers\PostController::class);
    Route::resource('permissions', App\Http\Controllers\PermissionController::class);
    Route::resource('roles', App\Http\Controllers\RoleController::class);
});

//rutas para el controlador Animal
Route::get('animal', [AnimalController::class, 'index'])->name('animal.index');
Route::post('animal', [AnimalController::class, 'registrar'])->name('animal.registrar');
Route::get('animal/eliminar/{id}', [AnimalController::class, 'eliminar'])->name('animal.eliminar');
Route::get('animal/editar/{id}', [AnimalController::class, 'editar'])->name('animal.editar');
Route::post('animal/actualizar', [AnimalController::class, 'actualizar'])->name('animal.actualizar');

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white"
    data-image="{{ asset('material') }}/img/sidebar-1.jpg">
    <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
    <div class="logo">
        <a href="https://creative-tim.com/" class="simple-text logo-normal">
            {{ __('Creative Tim') }}
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('home') }}">
                    <i class="material-icons">dashboard</i>
                    <p>{{ __('Dashboard') }}</p>
                </a>
            </li>
            <li class="nav-item {{ $activePage == 'profile' || $activePage == 'user-management' ? ' active' : '' }}">
                <a class="nav-link" data-toggle="collapse" href="#laravelExample" aria-expanded="true">
                    <i><img style="width:25px" src="{{ asset('img/laravel.svg') }}"></i>
                    <p>{{ __('Laravel Examples') }}
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse show" id="laravelExample">
                    <ul class="nav">
                        <li class="nav-item{{ $activePage == 'profile' ? ' active' : '' }}">
                            <a class="nav-link" href="#">
                                <span class="sidebar-mini"> UP </span>
                                <span class="sidebar-normal">{{ __('User profile') }} </span>
                            </a>
                        </li>
                        <li class="nav-item{{ $activePage == 'user-management' ? ' active' : '' }}">
                            <a class="nav-link" href="#">
                                <span class="sidebar-mini"> UM </span>
                                <span class="sidebar-normal"> {{ __('User Management') }} </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            @can('user_index')
                <li class="nav-item{{ $activePage == 'users' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('users.index') }}">
                        <i class="material-icons">content_paste</i>
                        <p>Usuarios</p>
                    </a>
                </li>
            @endcan
            @can('post_index')
                <li class="nav-item{{ $activePage == 'posts' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('posts.index') }}">
                        <i class="material-icons">library_books</i>
                        <p>{{ __('Post') }}</p>
                    </a>
                </li>
            @endcan
            @can('permission_index')
                <li class="nav-item{{ $activePage == 'permissions' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('permissions.index') }}">
                        <i class="material-icons">bubble_chart</i>
                        <p>{{ __('Permissions') }}</p>
                    </a>
                </li>
            @endcan
            @can('role_index')
                <li class="nav-item{{ $activePage == 'roles' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('roles.index') }}">
                        <i class="material-icons">location_ons</i>
                        <p>{{ __('Roles') }}</p>
                    </a>
                </li>
            @endcan
            <li class="nav-item{{ $activePage == 'animal' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('animal.index') }}">
                    <i class="material-icons">notifications</i>
                    <p>{{ __('Animals') }}</p>
                </a>
            </li>
            <li class="nav-item{{ $activePage == 'language' ? ' active' : '' }}">
                <a class="nav-link" href="#">
                    <i class="material-icons">language</i>
                    <p>{{ __('RTL Support') }}</p>
                </a>
            </li>
        </ul>
    </div>
</div>